//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Player
    {
        
        public int PlayerID { get; set; }
        [Required(ErrorMessage = "This is a required Field")]
        public string PlayerFirstName { get; set; }
        [Required(ErrorMessage = "This is a required Field")]
        public string PlayerLastName { get; set; }
        [Required(ErrorMessage = "This is a required Field")]
        public string Username { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This is a required Field")]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Confirm Password")]
        [Required(ErrorMessage = "This is a required Field")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

        [Required(ErrorMessage = "This is a required Field")]
        public string IGN { get; set; }
        [Required(ErrorMessage = "This is a required Field")]
        public string Rank { get; set; }
        [Required(ErrorMessage = "This is a required Field")]
        public string Role { get; set; }
        [Required(ErrorMessage = "This is a required Field")]
        public string UniversityName { get; set; }

        public string LoginError { get; set; }
    }
}
