//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fyp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string Player1IGN { get; set; }
        public string Player2IGN { get; set; }
        public string Player3IGN { get; set; }
        public string Player4IGN { get; set; }
        public string Player5IGN { get; set; }
    }
}
